config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :romantic_dates
  resources :activities
  

  get "/greeting", to: "welcomes#greeting"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :romantic_dates
  has_many :users, through: :romantic_dates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/romantic_date.rb
class RomanticDate < ApplicationRecord
  belongs_to :activity
  belongs_to :initiator, class_name: 'User'
  belongs_to :acceptor, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :romantic_dates
  has_many :activities, through: :romantic_dates
  
  has_many :initiated_dates, foreign_key: :initiator_id, class_name: 'RomanticDate', dependent: :destroy

  has_many :acceptors, through: :initiated_dates

  has_many :accepted_dates, foreign_key: :acceptor_id, class_name: 'RomanticDate', dependent: :destroy
  has_many :initators, through: :accepted_dates

  validates :name, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :find_activity, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def create
    activity = Activity.create(act_params)
    redirect_to activity_path(activity)
  end

  def edit
  end

  def update
    @activity.update(act_params)
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private 

  def act_params
    params.require(:activity).permit(:name, :location, :description, :has_meal, :has_alcohol)
  end

  def find_activity
  @activity = Activity.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/romantic_dates_controller.rb
class RomanticDatesController < ApplicationController

  before_action :find_romantic_date, only: [:show, :edit, :update, :destroy]

  def index
    @romanticdates = RomanticDate.all
  end

  def show
  end

  def new
    @romanticdate = RomanticDate.new
  end

  def create
    date = RomanticDate.create(date_params)
    redirect_to romantic_date_path(date)
  end

  def edit
  end

  def update
    @romanticdate.update(date_params)
    redirect_to romantic_date_path(@romanticdate)
  end

  def destroy
    @romanticdate.destroy
    redirect_to romantic_dates_path
  end


  private

  def date_params
    params.require(:romantic_date).permit(:initiator_id, :acceptor_id, :activity_id, :outcome)
  end

  def find_romantic_date
    @romanticdate = RomanticDate.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save    
    redirect_to user_path(@user)
    else 
      render :new
    end 

  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :hobby, :personality, :sign)
  end

  def find_user
    @user = User.find(params[:id])
  end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def greeting
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/romantic_dates_helper.rb
module RomanticDatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_activity_form.html.erb
<%= form_for @activity do |f| %>
  <%= f.label :name, "Activity Name:" %>
  <%= f.text_field :name %>
<br>
<br>
  <%= f.label :location, "Location:" %>
  <%= f.text_field :location %>
<br>
<br>
  <%= f.label :description, "Description:" %>
  <%= f.text_field :description %>
<br>
<br>
  <%= f.label :has_meal, "Meal?" %>
  <%= f.select :has_meal, [true, false] %>
<br>
<br>
  <%= f.label :has_alcohol, "Alcohol?" %>
  <%= f.select :has_alcohol, [true, false] %>
<br>
<br>
  <%= f.submit button_text %>
<% end %>

app/views/activities/edit.html.erb
<h2> Edit Date Activity </h2>

<%= render partial: "activity_form", locals: {button_text: "Edit Date Activity"} %>

app/views/activities/index.html.erb
<h1> All Activities </h1>

<div>
  <ul>
    <% @activities.each do |activity| %>
    <li> <%= link_to activity.name.titleize, activity_path(activity) %> </li>
    <% end %>
  </ul>
</div>

<%= link_to "Create New Activity", new_activity_path %>

app/views/activities/new.html.erb
<h2> Create Date Activity </h2>

<%= render partial: "activity_form", locals: {button_text: "Create Date Activity"} %>

app/views/activities/show.html.erb
<h2><%= @activity.name.titleize %></h2>

<div>
  <ul>
    <li> Location: <%= @activity.location.titleize %> </li>
    <li> Description: <%= @activity.description %>  </li>
    <li> Has Meal? <%= @activity.has_meal %>  </li>
    <li> Has Alcohol? <%= @activity.has_alcohol%>  </li>
  </ul>
</div>


<%= link_to "Edit Activity", edit_activity_path(@activity) %>
<br>
<%= link_to "Delete Activity", activity_path(@activity),
            method: "delete",
            data: {:confirm => "ARE YOU SURE?"} %>
            <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dating</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "header"> 
  <ul>
      <li> <%= link_to "Activity Homepage", activities_path %> </li>
      <li> <%= link_to "All Users Hompage", users_path %> </li>
      <li> <%= link_to "All Romantic Dates Homepage", romantic_dates_path %> </li>
  </ul>
  </div>

    <%= yield %>
  </body>
</html>

app/views/romantic_dates/_romantic_date_form.html.erb
  <%= form_for  @romanticdate do |f| %>
  <%= f.label :name, "Initiator:" %>
  <%= f.collection_select(:initiator_id, User.all, :id, :name)%>
  <%= f.label :name, "Acceptor:" %>
  <%= f.collection_select(:acceptor_id, User.all, :id, :name)%>
  <%= f.label :activity, "Activity" %>
  <%= f.collection_select(:activity_id, Activity.all, :id, :name) %>
  <%= f.label :outcome, "Outcome:" %>
  <%= f.text_field :outcome %>
  <%= f.submit button_text %>
<% end %>

app/views/romantic_dates/edit.html.erb
<h1>Edit Romantic Date</h1>

<%= render partial: "romantic_date_form", locals: {button_text: "Edit Romantic Date"} %>

app/views/romantic_dates/index.html.erb
<h1> All Romantic Dates </h1>

<div>
  <ul>
    <% @romanticdates.each do |romanticdate| %>
    <p><%= link_to "Romantic Date", romantic_date_path(romanticdate) %></p>
      <li> Initiator: <%= link_to romanticdate.initiator.name.titleize, user_path(romanticdate.initiator) %> </li>
      <li> Acceptor: <%= link_to romanticdate.acceptor.name.titleize, user_path(romanticdate.acceptor) %> </li>
      <li> Activity: <%= link_to romanticdate.activity.name.titleize, activity_path(romanticdate.activity)%> </li>
      <li> Outcome: <%= romanticdate.outcome %> </li>
      <br>
    <% end %>
  </ul>
</div>

app/views/romantic_dates/new.html.erb
<h1>Create Romantic Date</h1>

<%= render partial: "romantic_date_form", locals: {button_text: "Create New Romantic Date"} %>

app/views/romantic_dates/show.html.erb
<h1> <%= "#{@romanticdate.initiator.name.titlecase}" " & " "#{@romanticdate.acceptor.name.titlecase}" "'s " "Romantic Date" %> </h1>

<li> <%= @romanticdate.activity.name %> </li>
<li><%= @romanticdate.outcome %> </li>
<br>

<%= link_to "Edit Romantic Date", edit_romantic_date_path(@romanticdate) %>
<br>
<%= link_to  "Delete Romantic Date", romantic_date_path(@romanticdate),
                  method: "delete", 
                  data: {:confirm => "ARE YOU SURE?"} %>

app/views/users/_user_form.html.erb
<% if @user.errors %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>


<%= form_for @user do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :hobby, "Hobbies:" %>
  <%= f.text_field :hobby %>
  <br>
  <%= f.label :personality, "Myers-Brigg Personality:" %>
  <%= f.select :personality, options_for_select(["ISTJ - The Inspector",
                        "ISTP - The Crafter",
                        "ISFJ - The Protector", 
                        "ISFP - The Artist", 
                        "INFJ - The Advocate", 
                        "INFP - The Mediator", 
                        "INTJ - The Architect", 
                        "INTP - The Thinker",
                        "ESTP - The Persuader",
                        "ESTJ - The Director",
                        "ESFP - The Performer",
                        "ESFJ - The Caregiver",
                        "ENFP - The Champion",
                        "ENFJ - The Giver",
                        "ENTP - The Debater",
                        "ENTJ - The Commander"]), {}, class: "form-control" %>

  <br>
  <%= f.label :sign, "Zodiac Sign:" %>
  <%= f.select :sign, options_for_select(["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"]), {}, class: "form-control" %>
  <br>
  <%= f.submit button_text %>
<% end %>
<br>
<%= link_to "Back to Users", users_path%>

app/views/users/edit.html.erb
<h2> Edit User Form </h2>

<%= render partial: "user_form", locals: {button_text: "Edit User Form"} %>

app/views/users/index.html.erb
<h1> All Users </h1>

<div>
  <ul>
    <% @users.each do |user| %>
      <li> <%= link_to user.name.titleize, user_path(user) %> </li>
    <% end %>
  </ul>
</div>

<%= link_to "Create New User", new_user_path %>

app/views/users/new.html.erb
<h2> New User Form </h2>

<%= render partial: "user_form", locals: {button_text: "Submit New User"} %>

app/views/users/show.html.erb
<h2> <%= @user.name.capitalize %> </h2>

<div>
  <ul>
    <li> Hobbies: <%= @user.hobby %> </li>
    <li>Myers-Brigg Personality: <%= @user.personality %> </li>
    <li>Zodiac Sign: <%= @user.sign %> </li>
  </ul>
 </div>

<%= link_to "Edit User Page", edit_user_path %>
<br>
<%= link_to "Delete User", user_path(@user),
            method: "delete", 
            data: {:confirm => "ARE YOU SURE? NO MORE DATES?"} %>
            <br>

app/views/welcomes/greeting.html.erb
<h1> Welcome!! </h1>